version: '3.8'

services:
  # Development environment
  dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

  # Production environment
  prod:
    build:
      context: .
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    command: npm start
    restart: unless-stopped