version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: development
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: bun run dev

  # Production service
  app-prod:
    build:
      context: .
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    command: bun start